apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: tokafka
  namespace: energy-amqbroker
  labels:
    app: energy
spec:
  addressName: tokafka
  queueName: tokafka
  removeFromBrokerOnDelete: true
  routingType: anycast
