apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: fromamqp
  namespace: energy-kafka
  labels:
    strimzi.io/cluster: energy-cluster
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 5
  replicas: 1
