apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  namespace: energy-amqbroker
  name: energy-broker
  labels:
    app: energy
  application: ex-aao-app
spec:
  acceptors:
    - port: 5672
      expose: true
      protocols: 'true'
      name: amqp
      enabledProtocols: amqp
  adminPassword: 
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    journalType: nio
    image: >-
      registry.redhat.io/amq7/amq-broker@sha256:a6a2fd548f4e89151a8e7d4bacb7380d0076bbd1b1f5bc5555f2e95e19e1441f
    storage:
      size: 1Gi
    jolokiaAgentEnabled: false
    managementRBACEnabled: true
  console:
    expose: true
  adminUser: 
